#!/bin/sh

if ! java -jar gui/dist/gui.jar ; then
  echo "Java is not installed"
  sudo add-apt-repository ppa:webupd8team/java
  sudo apt update
  sudo apt-get install oracle-java8-installer
  export JAVA_HOME="/usr/lib/jvm/java-8-oracle"
  java -jar gui/dist/gui.jar
fi
