#!/bin/sh

# echo $0 #>> log
sleep 1
echo $1 #>> log
sleep 1
echo $2 #>> log
sleep 1
echo $3 #>> log
sleep 1
echo "end" #>> log


# while true; do
#   wait 1000
#   echo "hello world"
# done
#   #statements
