/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.GridLayout;
import javax.swing.SwingConstants;

/**
 *
 * @author thor
 */
public class mianFrame extends javax.swing.JFrame {

  private String welcomeText = "Welcome to the linux installer";
  private String welcomeDiscrption = "<html><center>This installer will install any<br/>"
          + "required programs and configure your<br/>"
          + "environment so it’s ready to use. Enjoy 😃</center></html>";

  String username = System.getProperty("user.name");

  /**
   * Creates new form mianFrame
   */
  public mianFrame() {
    initComponents();
//    jPanel1.setLayout(new GridLayout());
    welcomeTextLabel.setText(welcomeText);
    welcomeDiscriotnLabel.setText(welcomeDiscrption);
    welcomeDiscriotnLabel.setHorizontalTextPosition(SwingConstants.CENTER);
    welcomeNameTexField.setText(username);
//    welcomeTextLabel.setVerticalAlignment(SwingConstants.LEFT); //added
//    welcomeTextLabel.setHorizontalAlignment(welcomeTextLabel.CENTER);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    logoLabel = new javax.swing.JLabel();
    welcomePanel = new javax.swing.JPanel();
    welcomeTextLabel = new javax.swing.JLabel();
    welcomeDiscriotnLabel = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    welcomeNameTexField = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    welcomePasswordField = new javax.swing.JPasswordField();
    jLabel2 = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    welcomeButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    logoLabel.setIcon(new javax.swing.ImageIcon("/home/thor/install_script/resources/company/logo.png")); // NOI18N

    welcomePanel.setLayout(new java.awt.GridLayout(5, 3));

    welcomeTextLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    welcomeTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    welcomeTextLabel.setText("Welcome to the linux installer");
    welcomeTextLabel.setName("welcomeTextLabel"); // NOI18N
    welcomePanel.add(welcomeTextLabel);

    welcomeDiscriotnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    welcomeDiscriotnLabel.setText("sadddfsdf");
    welcomeDiscriotnLabel.setName(""); // NOI18N
    welcomePanel.add(welcomeDiscriotnLabel);

    welcomeNameTexField.setToolTipText("Type your Linux user name");

    jLabel1.setText("Linux username");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap(19, Short.MAX_VALUE)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(welcomeNameTexField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(49, 49, 49))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap(19, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(welcomeNameTexField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel1))
        .addContainerGap())
    );

    welcomePanel.add(jPanel1);

    welcomePasswordField.setToolTipText("Type your Linux user password");
    welcomePasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        welcomePasswordFieldKeyPressed(evt);
      }
    });

    jLabel2.setText("Linux password");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addContainerGap(20, Short.MAX_VALUE)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(welcomePasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(50, 50, 50))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(welcomePasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2))
        .addContainerGap(21, Short.MAX_VALUE))
    );

    welcomePanel.add(jPanel2);

    welcomeButton.setText("Next");
    welcomeButton.setEnabled(false);
    welcomeButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        welcomeButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        .addContainerGap(305, Short.MAX_VALUE)
        .addComponent(welcomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(14, 14, 14))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(welcomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        .addContainerGap())
    );

    welcomePanel.add(jPanel3);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(welcomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(logoLabel)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(logoLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(welcomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
        .addContainerGap())
    );

    setBounds(0, 0, 417, 337);
  }// </editor-fold>//GEN-END:initComponents


  private void welcomePasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_welcomePasswordFieldKeyPressed
    if (!welcomeNameTexField.getText().isEmpty() || welcomePasswordField.getPassword().length > 0) {
      welcomeButton.setEnabled(true);
    } else {
      welcomeButton.setEnabled(false);

    }
  }//GEN-LAST:event_welcomePasswordFieldKeyPressed

  private void welcomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_welcomeButtonActionPerformed
    welcomePanel.setVisible(false);
  }//GEN-LAST:event_welcomeButtonActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(mianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(mianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(mianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(mianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new mianFrame().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JLabel logoLabel;
  private javax.swing.JButton welcomeButton;
  private javax.swing.JLabel welcomeDiscriotnLabel;
  private javax.swing.JTextField welcomeNameTexField;
  private javax.swing.JPanel welcomePanel;
  private javax.swing.JPasswordField welcomePasswordField;
  private javax.swing.JLabel welcomeTextLabel;
  // End of variables declaration//GEN-END:variables
}
