#!/bin/sh


echo "Hello from Update script"

echo $3 | sudo -S apt -y update
echo $3 | sudo -S apt -y upgrade
# sudo apt update
# sudo


# # echo $0 #>> log
# sleep 1
# echo "1 --> $1" #>> log
# sleep 1
# echo "2 --> $2" #>> log
# sleep 1
# echo "3 --> $3" #>> log
# sleep 1
# echo "end" #>> log
