#!/bin/bash

if [ "$1" == "-h" ]; then
  echo "Xillinx ISE 14.2"
  exit 0
fi


. resources/worker_scripts/helpers

##### Change this if version in archive change
XILLINX_INSTALLER_PATH="archive/Xilinx_ISE_DS_Lin_14.2_P.28xd.3.0/xsetup"


echo $3 | sudo -S $XILLINX_INSTALLER_PATH


### Adding paths
echo "Adding to path Xillinx paths"
echo "PATH=\$PATH:/opt/Xilinx/14.2/ISE_DS/ISE/bin/lin64/" >> ~/.bashrc
echo "PATH=\$PATH:/opt/Xilinx/current/ISE_DS/ISE/bin/lin64" >> ~/.bashrc
if [ -f ~/.zshrc ]; then
    echo "Using ZSH ... added to .zshrc"
    echo "PATH=\$PATH:/opt/Xilinx/14.2/ISE_DS/ISE/bin/lin64/" >> ~/.zshrc
    echo "PATH=\$PATH:/opt/Xilinx/current/ISE_DS/ISE/bin/lin64/" >> ~/.zshrc
fi




#####  Installs cable drivers
echo $3 | sudo -S apt -y install libusb-dev libc6-dev fxload
cd /opt/Xilinx
echo $3 | sudo -S git clone git://git.zerfleddert.de/usb-driver
cd usb-driver
echo $3 | sudo -S make
echo $3 | sudo ./setup_pcusb /opt/Xilinx/14.2/ISE_DS/ISE/
# echo $3 | sudo -S /opt/Xilinx/14.2/ISE_DS/ISE/bin/lin64/install_script/install_drivers/install_drivers
