#!/bin/bash

if [ "$1" == "-h" ]; then
  echo "Add Rovsing's Xillinx licence exports to the \"rc\" files"
  exit 0
fi

######## Build stuff #####
### Adding paths
echo "Adding Rovsing licence file on server"
echo "export XILINXD_LICENSE_FILE=2100@10.0.100.44" >> ~/.bashrc
echo "export LM_LICENSE_FILE=2100@10.0.100.44" >> ~/.bashrc
if [ -f ~/.zshrc ]; then
    echo "Using ZSH ... added to .zshrc"
    echo "export XILINXD_LICENSE_FILE=2100@10.0.100.44" >> ~/.zshrc
    echo "export LM_LICENSE_FILE=2100@10.0.100.44" >> ~/.zshrc
fi


echo $3 | sudo -S ln -s /opt/Xilinx/14.2 /opt/Xilinx/current
