#!/bin/bash

if [ "$1" == "-h" ]; then
  echo "Xillinx ISE 14.2"
  exit 0
fi


. resources/worker_scripts/helpers


# wget_forInstaller http://download.altera.com/akdlm/software/acdsinst/17.1/240/ib_installers/ModelSimProSetup-17.1.0.240-linux.run
