#!/bin/bash

if [ "$1" == "-h" ]; then
  echo "Add source for QOL scripts to the \"rc\" files"
  exit 0
fi

sed -e '/ZSH_THEME=/s/^/#/g' -i ~/.zshrc
sed -e '/plugins=(/s/^/#/g' -i ~/.zshrc
sed -e '/  git/s/^/#/g' -i ~/.zshrc
sed -e '/)/s/^/#/g' -i ~/.zshrc
sed -e '/source $ZSH\/oh-my-zsh.sh/s/^/#/g' -i ~/.zshrc

echo "####### To source QOL scripts ######" >> ~/.zshrc
echo "source ~/scripts/zshrc_stuff" >> ~/.zshrc
echo "source \$ZSH/oh-my-zsh.sh" >> ~/.zshrc
echo "PATH=\$PATH:~/scripts/" >> ~/.zshrc
